"""initial schema

Revision ID: 4d08fa6428e9
Revises: b7a406624397
Create Date: 2026-07-07 12:04:55.768998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4d08fa6428e9'
down_revision: Union[str, Sequence[str], None] = 'b7a406624397'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('email'), table_name='professor')
    op.drop_table('professor')
    op.drop_table('course')
    op.drop_table('department')
    op.drop_table('enrollment')
    op.drop_index(op.f('email'), table_name='student')
    op.drop_table('student')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('student_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('enrollment_year', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dept_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['dept_id'], ['department.dept_id'], name=op.f('student_ibfk_1')),
    sa.PrimaryKeyConstraint('student_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('email'), 'student', ['email'], unique=True)
    op.create_table('enrollment',
    sa.Column('enrollment_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('course_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('grade', mysql.VARCHAR(length=5), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.course_id'], name=op.f('enrollment_ibfk_2')),
    sa.ForeignKeyConstraint(['student_id'], ['student.student_id'], name=op.f('enrollment_ibfk_1')),
    sa.PrimaryKeyConstraint('enrollment_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('department',
    sa.Column('dept_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('dept_name', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('dept_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('course',
    sa.Column('course_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('course_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('credits', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('course_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('professor',
    sa.Column('professor_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('professor_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('email'), 'professor', ['email'], unique=True)
    # ### end Alembic commands ###
