"""initial schema

Revision ID: b7a406624397
Revises: 6c659bbc8517
Create Date: 2026-07-07 11:57:45.377891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b7a406624397'
down_revision: Union[str, Sequence[str], None] = '6c659bbc8517'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('department_name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('department_id')
    )
    op.create_table('professors',
    sa.Column('professor_id', sa.Integer(), nullable=False),
    sa.Column('professor_name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('professor_id')
    )
    op.create_table('courses',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('course_name', sa.String(length=100), nullable=True),
    sa.Column('professor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['professor_id'], ['professors.professor_id'], ),
    sa.PrimaryKeyConstraint('course_id')
    )
    op.create_table('students',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('student_name', sa.String(length=100), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.department_id'], ),
    sa.PrimaryKeyConstraint('student_id')
    )
    op.create_table('enrollments',
    sa.Column('enrollment_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ),
    sa.PrimaryKeyConstraint('enrollment_id')
    )
    op.drop_table('course')
    op.drop_index(op.f('email'), table_name='professor')
    op.drop_table('professor')
    op.drop_table('enrollment')
    op.drop_table('department')
    op.drop_index(op.f('email'), table_name='student')
    op.drop_table('student')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('student_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('enrollment_year', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dept_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['dept_id'], ['department.dept_id'], name=op.f('student_ibfk_1')),
    sa.PrimaryKeyConstraint('student_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('email'), 'student', ['email'], unique=True)
    op.create_table('department',
    sa.Column('dept_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('dept_name', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('dept_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('enrollment',
    sa.Column('enrollment_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('course_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('grade', mysql.VARCHAR(length=5), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.course_id'], name=op.f('enrollment_ibfk_2')),
    sa.ForeignKeyConstraint(['student_id'], ['student.student_id'], name=op.f('enrollment_ibfk_1')),
    sa.PrimaryKeyConstraint('enrollment_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('professor',
    sa.Column('professor_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('professor_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('email'), 'professor', ['email'], unique=True)
    op.create_table('course',
    sa.Column('course_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('course_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('credits', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('course_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('enrollments')
    op.drop_table('students')
    op.drop_table('courses')
    op.drop_table('professors')
    op.drop_table('departments')
    # ### end Alembic commands ###
